S3_BUCKET_PATH="${AICHOR_OUTPUT_PATH}"

python -m pretraining.pretrain   experiment=hg38/hg38  \
        dataset.max_length=12000\
        dataset.batch_size=1\
        dataset.batch_size_eval=1\
        dataset.mlm=true \
        dataset.shuffle=true \
        dataset.mlm_probability=0.15 \
        dataset.rc_aug=false \
        dataset.num_workers=4\
        model=caduceus \
        model.config.d_model=768 \
        model.config.n_layer=12\
        model.config.bidirectional=true \
        model.config.bidirectional_strategy=add \
        model.config.bidirectional_weight_tie=true \
        model.config.rcps=true \
        optimizer.lr="8e-4" \
        trainer.max_steps=10000\
        trainer.log_every_n_steps=1 \
        trainer.devices=1\
        trainer.accumulate_grad_batches=88\
        trainer.num_sanity_val_steps=1\
        trainer.profiler=simple \
        trainer.limit_val_batches=500 \
        +trainer.val_check_interval=1000\
        +trainer.detect_anomaly=true\
        wandb.project="caduceus-hg38" \
        train.monitor="validation/loss" \
        callbacks.model_checkpoint.dirpath=${S3_BUCKET_PATH}\

